#!/bin/sh
# Same rationale as 71_init_etc_ramfs: skip the ramfs mount over /www/tmp
# when we've successfully pivoted to a UBIFS overlay.

RAMFS_WWW_DIRS="/www/tmp/"

rootfs_init_www_ramfs(){
    check_skip && return 0
    for dir in $RAMFS_WWW_DIRS; do
        tmp_dir=/tmp/`basename ${dir}`_tmp
        cp -a ${dir} ${tmp_dir}
        mount -t ramfs -n none ${dir}
        cp -a ${tmp_dir}/* ${dir}
        rm -rf ${tmp_dir}
    done
}

boot_hook_add preinit_mount_root rootfs_init_www_ramfs
